### ISSUE TITLE
helm chart for patroni replication starts init container with high value of memory limit

### ISSUE THREAD

**Issue by pankaj-cgi** [bashbang/cloudops#12]
We have the option to change the resource limits in values-gold.yaml and values-golddr.yaml. These values update the container but init containers are starting with high values or hard coded values of resources. 
I had these values: stateful_requests_cpu: 50m
stateful_requests_memory: 50Mi
stateful_limit_cpu: 200m
stateful_limit_memory: 250Mi
But init container started with 1Gi of memory limit.

![image](https://user-images.githubusercontent.com/79924447/233215854-6f5e5065-3423-4117-863c-08263a507ea4.png)

This causes overutilization in low resource projects and pods fail to start up

**Comment by bashbang** [comment]
Ya so it's pulling the limits and requests from the k8s defaults I think.

You should be able to just add a "resources:" section with cpu and memory defined for the requests and limits and then should be good to go.

**Comment by bashbang** [comment]
Made a PR: https://github.com/bashbang/cloudops/pull/13

I don't have an active install of this config so please give this a test run and let me know if it works and I'll get that into the code base.
